s/"RC CARS"/"Rotor-Racing"/g
s/<STRONG>Car /<STRONG>Team /g
s/00397B/F0652F/g
s/Results generated by LAPS FREE - <A HREF="http:\/\/www.rctiming.com" TARGET="resource window">www.rctiming.com<\/A>/Professional Racing Solutions by Rotor-Racing - <A HREF="http:\/\/www.rotor-racing.com" TARGET="resource window">www.rotor-racing.com<\/A>/g